version: "3"

services:
  pingdatagov-pap:
    image: pricecs/pingdatagov-pap:8.0
    env_file:
      - ./env_vars
    volumes:
    # This volume injects a DG license file into the container that is used by setup
      - ./pingdatagov-pap/volumes/PingDataGovernance.lic:/opt/pap/PingDataGovernance-PAP/PingDataGovernance.lic
    ports:
      - 9443:9443
    networks:
      - pingnet

  pap-config:
    image: postman/newman:latest
    command:
      run https://www.getpostman.com/collections/18d685d285ea7fb92886 --insecure
    networks:
      - pingnet 

  pingdatagov:
    image: pingidentity/pingdatagovernance:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:    
      # Adding the bits needed for Jokes API and PF Token Validation
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-DataGov.git
      - SERVER_PROFILE_PATH=datagov
      - SERVER_PROFILE_PARENT=BASELINE
      # Using the GTE initial profile
      - SERVER_PROFILE_BASELINE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASELINE_PATH=baseline/pingdatagovernance
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    ports:
      - 7443:443
    networks:
      - pingnet

  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-PF-Base.git
      - SERVER_PROFILE_PATH=pingfed
      - VERBOSE=false
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ~/.pingidentity/devops
      - ./env_vars
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingfederate:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-PD-Base.git
      - SERVER_PROFILE_PATH=pingdir
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingdirectory:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in

    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-DataGov.git
      - SERVER_PROFILE_PATH=pingdir
    ports:
      - 8443:8443
    networks:
      - pingnet

networks:
    pingnet:
